apiVersion: v1
kind: ConfigMap
metadata:
  namespace: litellm
  name: config-yaml
data:
  config.yaml: |
    model_list:
      - model_name: gpt-5
        litellm_params:
          model: openai/gpt-5
          api_key: os.environ/OPENAI_API_KEY
