apiVersion: v1
kind: ConfigMap
metadata:
  namespace: litellm
  name: config-yaml
data:
  config.yaml: |
    model_list:
      - model_name: claude-sonnet-4-5
        litellm_params:
          model: anthropic/claude-sonnet-4-5
          api_key: os.environ/ANTHROPIC_API_KEY
